export let duels = [
  // {
  //   id: "10",
  //   playerOneId: 1,
  //   playerTwoId: 0,
  //   challengerId: 1,
  //   challengeTakerId: 0,
  //   playlist: 1,
  //   challengerScore: 55,
  //   challengeTakerScore: 0,
  //   playerOneTotalScore: 2,
  //   playerTwoTotalScore: 3,
  //   rounds: {
  //     0: {
  //       songs: ["Kiše jesenje", "Kap po kap", "Marija", "Ja sam budućnost"],
  //       correctAnswer: "Kap po kap",
  //       playerAnswer: "Marija",
  //       playerPointsEarned: 0,
  //       playerTimeAnswered: 3,
  //       // audio: require("./assets/clips/Divlje_jagode_-_Kap_po_kap-cut.mp3"),
  //     },
  //     1: {
  //       songs: [
  //         "Vatra",
  //         "Divlje jagode",
  //         "Parni valjak",
  //         "Bajaga i Instruktori",
  //       ],
  //       correctAnswer: "Parni valjak",
  //       playerAnswer: "Parni valjak",
  //       playerPointsEarned: 40,
  //       playerTimeAnswered: 4,
  //       // audio: require("./assets/clips/Parni_valjak_-_Sve_još_miriše_na_nju-cut.mp3"),
  //     },
  //     2: {
  //       songs: [
  //         "Ne zovi mama doktora",
  //         "Ja volim samo sebe",
  //         "Previše suza u mom pivu",
  //         "Teške boje",
  //       ],
  //       correctAnswer: "Previše suza u mom pivu",
  //       playerAnswer: "Ja volim samo sebe",
  //       playerPointsEarned: 0,
  //       playerTimeAnswered: 2,
  //       // audio: require("./assets/clips/Prljavo_kazaliste_-_Previše_suza_u_mom_pivu-cut.mp3"),
  //     },
  //   },
  //   yourScore: 0,
  // },
  // {
  //   id: "21",
  //   playerOneId: 2,
  //   playerTwoId: 1,
  //   challengerId: 2,
  //   challengeTakerId: 1,
  //   playlist: 0,
  //   challengerScore: 24,
  //   challengeTakerScore: 0,
  //   playerOneTotalScore: 1,
  //   playerTwoTotalScore: 1,
  //   rounds: {
  //     0: {
  //       songs: ["Kiše jesenje", "Kap po kap", "Marija", "Ja sam budućnost"],
  //       correctAnswer: "Kap po kap",
  //       correctAnswerId: 0,
  //       playerAnswer: "Marija",
  //       playerPointsEarned: 0,
  //       playerTimeAnswered: 3,
  //       // audio: require("./assets/clips/Divlje_jagode_-_Kap_po_kap-cut.mp3"),
  //     },
  //     1: {
  //       songs: [
  //         "Vatra",
  //         "Divlje jagode",
  //         "Parni valjak",
  //         "Bajaga i Instruktori",
  //       ],
  //       correctAnswer: "Parni valjak",
  //       correctAnswerId: 2,
  //       playerAnswer: "Parni valjak",
  //       playerPointsEarned: 40,
  //       playerTimeAnswered: 4,
  //       // audio: require("./assets/clips/Parni_valjak_-_Sve_još_miriše_na_nju-cut.mp3"),
  //     },
  //     2: {
  //       songs: [
  //         "Ne zovi mama doktora",
  //         "Ja volim samo sebe",
  //         "Previše suza u mom pivu",
  //         "Teške boje",
  //       ],
  //       correctAnswer: "Previše suza u mom pivu",
  //       correctAnswerId: 3,
  //       playerAnswer: "Ja volim samo sebe",
  //       playerPointsEarned: 0,
  //       playerTimeAnswered: 2,
  //       // audio: require("./assets/clips/Prljavo_kazaliste_-_Previše_suza_u_mom_pivu-cut.mp3"),
  //     },
  //   },
  //   yourScore: 0,
  // },
];
