const path =
  "C:/Users/ekoko/Desktop/Projects/songpop-balkans-backend/src/assets/clips";

export const songs = [
  {
    id: 0,
    title: "Kap po kap",
    artist: "Divlje Jagode",
    playlist: "rock",
    file: `${path}/Divlje_jagode_-_Kap_po_kap-cut.mp3`,
  },
  {
    id: 1,
    title: "Marija",
    artist: "Divlje Jagode",
    playlist: "rock",
    file: `${path}/Divlje_jagode_-_Marija-cut.mp3`,
  },
  {
    id: 2,
    title: "Sve još miriše na nju",
    artist: "Parni valjak",
    playlist: "rock",
    file: `${path}/Parni_valjak_-_Sve_još_miriše_na_nju-cut.mp3`,
  },
  {
    id: 3,
    title: "Previše suza u mom pivu",
    artist: "Prljavo kazalište",
    playlist: "rock",
    file: `${path}/Prljavo_kazaliste_-_Previše_suza_u_mom_pivu-cut.mp3`,
  },
  {
    id: 4,
    title: "Aspirin",
    artist: "Seka",
    playlist: "folk",
    file: `${path}/Seka_-_Aspirin-cut.mp3`,
  },
  {
    id: 5,
    title: "Mešaj, mala (feat. Saša Matić)",
    artist: "Rada Manojlović",
    playlist: "folk",
    file: `${path}/Rada_Manojlović_-_Mešaj,_mala_feat._Saša_Matić-cut.mp3`,
  },
  {
    id: 6,
    title: "Šampanjac",
    artist: "Mile Kitić",
    playlist: "folk",
    file: `${path}/Mile_Kitić_-_Šampanjac-cut.mp3`,
  },
  {
    id: 7,
    title: "Trezan",
    artist: "Sinan Sakić",
    playlist: "folk",
    file: `${path}/Sinan_Sakić_-_Trezan-cut.mp3`,
  },
  // {
  //   id: 8,
  //   title: "No sikiriki no",
  //   artist: "Edo Maajka",
  //   playlist: "rap",
  //   file: `${path}\\Edo_Maajka_-_No_sikiriki_no.mp3`,
  // },
  // {
  //   id: 9,
  //   title: "Ne može",
  //   artist: "Vojko V",
  //   playlist: "rap",
  //   file: `${path}\\Vojko_V_-_Ne_može.mp3`,
  // },
  // {
  //   id: 10,
  //   title: "Esi mi dobar",
  //   artist: "Bad Copy",
  //   playlist: "rap",
  //   file: `${path}\\Bad_Copy_-_Esi_mi_dobar.mp3`,
  // },
  // {
  //   id: 11,
  //   title: "Malo san maka",
  //   artist: "The Beat Fleet",
  //   playlist: "rap",
  //   file: `${path}\\The_Beat_Fleet_-_Malo_san_maka.mp3`,
  // },
  {
    id: 12,
    title: "Kiše jesenje",
    artist: "Prljavo kazalište",
    playlist: "rock",
    file: `${path}\\Prljavo_kazalište_-_Kiše_jesenje-cut.mp3`,
  },
  {
    id: 13,
    title: "Ja sam budućnost",
    artist: "Majke",
    playlist: "rock",
    file: `${path}\\Majke_-_Ja_sam_budućnost-cut.mp3`,
  },
  {
    id: 14,
    title: "Verujem, ne verujem",
    artist: "Bajaga i Instruktori",
    playlist: "rock",
    file: `${path}\\Bajaga_i_Instruktori_-_Verujem,_ne_verujem-cut.mp3`,
  },
  {
    id: 15,
    title: "Ne zovi mama doktora",
    artist: "Prljavo kazalište",
    playlist: "rock",
    file: `${path}\\Prljavo_kazalište_-_Ne_zovi_mama_doktora-cut.mp3`,
  },
  {
    id: 16,
    title: "Ja volim samo sebe",
    artist: "Psihomodo Pop",
    playlist: "rock",
    file: `${path}\\Psihomodo_Pop_-_Ja_volim_samo_sebe-cut.mp3`,
  },
  {
    id: 17,
    title: "Teške boje",
    artist: "Goran Bare i Majke",
    playlist: "rock",
    file: `${path}\\Goran_Bare_i_Majke_-_Teške_boje-cut.mp3`,
  },
  {
    id: 18,
    title: "Što si mi u kavu stavila",
    artist: "Pađen band",
    playlist: "rock",
    file: `${path}\\Pađen_band_-_Što_si_mi_u_kavu_stavila-cut.mp3`,
  },
  {
    id: 19,
    title: "Napile se ulice",
    artist: "Bijelo dugme",
    playlist: "rock",
    file: `${path}\\Bijelo_dugme_-_Napile_se_ulice-cut.mp3`,
  },
  {
    id: 20,
    title: "Mali signali",
    artist: "Nataša Bekvalac",
    playlist: "folk",
    file: `${path}\\Nataša_Bekvalac_-_Mali_signali-cut.mp3`,
  },
  /****21************************************************************/
  {
    id: 21,
    title: "Bele ruže",
    artist: "Aca Lukas",
    playlist: "folk",
    file: `${path}\\Aca_Lukas_-_Bele_ruže-cut.mp3`,
  },
  {
    id: 22,
    title: "Ponovo",
    artist: "Nataša Bekvalac",
    playlist: "folk",
    file: `${path}\\Nataša_Bekvalac_-_Ponovo-cut.mp3`,
  },
  {
    id: 23,
    title: "Litar na litar",
    artist: "Đani",
    playlist: "folk",
    file: `${path}\\Đani_-_Litar_na_litar-cut.mp3`,
  },
  {
    id: 24,
    title: "Zicer",
    artist: "Olja Karleuša",
    playlist: "folk",
    file: `${path}\\Olja_Karleuša_-_Zicer-cut.mp3`,
  },
  {
    id: 25,
    title: "Vrati mi se nesrećo",
    artist: "Miligram 3",
    playlist: "folk",
    file: `${path}\\Miligram_3_-_Vrati_mi_se_nesrećo-cut.mp3`,
  },
  {
    id: 26,
    title: "Hitna pomoć",
    artist: "Trik FX",
    playlist: "folk",
    file: `${path}\\Trik_FX_-_Hitna_pomoć-cut.mp3`,
  },
  {
    id: 27,
    title: "Gljiva ludara",
    artist: "Đogani",
    playlist: "folk",
    file: `${path}\\Đogani_-_Gljiva_ludara-cut.mp3`,
  },
  {
    id: 28,
    title: "Chicago",
    artist: "Jura Stublić i Film",
    playlist: "rock",
    file: `${path}/Jura_Stublić_i_Film_-_Chicago-cut.mp3`,
  },
  {
    id: 29,
    title: "Srce na cesti",
    artist: "Jura Stublić i Film",
    playlist: "rock",
    file: `${path}/Jura_Stublić_i_Film_-_Srce_na_cesti-cut.mp3`,
  },
  {
    id: 30,
    title: "Tremolo",
    artist: "Vatra",
    playlist: "rock",
    file: `${path}\\Vatra_-_Tremolo-cut.mp3`,
  },
  /****31************************************************************/
  {
    id: 31,
    title: "Ća bin da",
    artist: "Gustafi",
    playlist: "istra",
    file: `${path}\\Gustafi_-_Ća_bin_da-cut.mp3`,
  },
  {
    id: 32,
    title: "Con la supa istriana",
    artist: "Elio Pisak",
    playlist: "istra",
    file: `${path}\\Elio_Pisak_-_Con_la_supa_istriana-cut.mp3`,
  },
  {
    id: 33,
    title: "Imam malu kako i cvit",
    artist: "Duo magnolija",
    playlist: "istra",
    file: `${path}\\Duo_magnolija_-_Imam_malu_kako_i_cvit-cut.mp3`,
  },
  {
    id: 34,
    title: "Mens sana in malvasia istriana",
    artist: "Gori Ussi Winnetou",
    playlist: "istra",
    file: `${path}\\Gori_Ussi_Winnetou_-_Mens_sana_in_malvasia_istriana-cut.mp3`,
  },
  {
    id: 35,
    title: "Addio Pola",
    artist: "Gori Ussi Winnetou",
    playlist: "istra",
    file: `${path}\\Gori_Ussi_Winnetou-_Addio_Pola-cut.mp3`,
  },
  {
    id: 36,
    title: "Brkica",
    artist: "Gustafi",
    playlist: "istra",
    file: `${path}\\Gustafi_-_Brkica-cut.mp3`,
  },
  {
    id: 37,
    title: "Kurijera",
    artist: "Gustafi",
    playlist: "istra",
    file: `${path}\\Gustafi_-_Kurijera-cut.mp3`,
  },
  {
    id: 38,
    title: "Gušti su gušti",
    artist: "Alen Vitasović",
    playlist: "istra",
    file: `${path}\\Alen_Vitasović_-_Gušti_su_gušti-cut.mp3`,
  },
  {
    id: 39,
    title: "Istrijan",
    artist: "Alen Vitasović",
    playlist: "istra",
    file: `${path}\\Alen_Vitasović_-_Istrijan-cut.mp3`,
  },
  {
    id: 40,
    title: "Ja ne gren",
    artist: "Alen Vitasović",
    playlist: "istra",
    file: `${path}\\Alen_Vitasović_-_Ja_ne_gren-cut.mp3`,
  },
  /****41************************************************************/
  {
    id: 41,
    title: "Ja sjećam se",
    artist: "KUD Idijoti",
    playlist: "rock",
    file: `${path}\\KUD_Idijoti_-_Ja_sjećam_se-cut.mp3`,
  },
  {
    id: 42,
    title: "Jenu noć",
    artist: "Alen Vitasović",
    playlist: "istra",
    file: `${path}\\Alen_Vitasović_-_Jenu_noć-cut.mp3`,
  },
  {
    id: 43,
    title: "Katarina",
    artist: "Gustafi",
    playlist: "istra",
    file: `${path}\\Gustafi_-_Katarina-cut.mp3`,
  },
  {
    id: 44,
    title: "Bonbon",
    artist: "Koktelsi",
    playlist: "istra",
    file: `${path}\\Koktelsi_-_Bonbon-cut.mp3`,
  },
  {
    id: 45,
    title: "Bandiera rossa",
    artist: "KUD Idijoti",
    playlist: "istra",
    file: `${path}\\KUD_Idijoti_-_Bandiera_rossa-cut.mp3`,
  },
  {
    id: 46,
    title: "L'armonica triestina",
    artist: "Elio Pisak",
    playlist: "istra",
    file: `${path}\\Elio_Pisak_-_L'armonica_triestina-cut.mp3`,
  },
  {
    id: 47,
    title: "More dimboko, nebo visoko",
    artist: "Livio Morosin",
    playlist: "istra",
    file: `${path}\\Livio_Morosin_-_More_dimboko,_nebo_visoko-cut.mp3`,
  },
  {
    id: 48,
    title: "Niš mi se ne da",
    artist: "Alen Vitasović",
    playlist: "istra",
    file: `${path}\\Alen_Vitasović_-_Niš_mi_se_ne_da-cut.mp3`,
  },
  {
    id: 49,
    title: "Noći istarske",
    artist: "Sergio Pavat",
    playlist: "istra",
    file: `${path}\\Sergio_Pavat_-_Noći_istarske-cut.mp3`,
  },
  {
    id: 50,
    title: "Ređipet kolor de rosa",
    artist: "Sergio Pavat",
    playlist: "istra",
    file: `${path}\\Sergio_Pavat_-_Ređipet_kolor_de_rosa-cut.mp3`,
  },
  /****51************************************************************/
  {
    id: 51,
    title: "Rege na brege (feat. Franci Blašković)",
    artist: "Šajeta",
    playlist: "istra",
    file: `${path}\\Šajeta_-_Rege_na_brege_feat._Franci_Blašković-cut.mp3`,
  },
  {
    id: 52,
    title: "Sexuvalna",
    artist: "Tamara Obrovac & Transhistria Electric",
    playlist: "istra",
    file: `${path}\\Tamara_Obrovac_&_Transhistria_Electric_-_Sexuvalna-cut.mp3`,
  },
  {
    id: 53,
    title: "Puna je Pula",
    artist: "Duo magnolija",
    playlist: "istra",
    file: `${path}\\Duo_magnolija_-_Puna_je_Pula-cut.mp3`,
  },
  {
    id: 54,
    title: "Cilu noć na tebe mala san pensa",
    artist: "Duo magnolija",
    playlist: "istra",
    file: `${path}\\Duo_magnolija_-_Cilu_noć_na_tebe_mala_san_pensa-cut.mp3`,
  },
];
