const path = "C:\\Users\\ekoko\\Downloads";
const newPath =
  "C:/Users/ekoko/Desktop/Projects/songpop-balkans-backend/src/assets/clips";

export const songs = [
  {
    id: 0,
    title: "Kap po kap",
    artist: "Divlje Jagode",
    playlist: "rock",
    // file: `${path}\\Divlje_jagode_-_Kap_po_kap.mp3`,
    file: `${newPath}/Divlje_jagode_-_Kap_po_kap-cut.mp3`,
  },
  {
    id: 1,
    title: "Marija",
    artist: "Divlje Jagode",
    playlist: "rock",
    // file: `${path}\\Divlje_jagode_-_Marija.mp3`,
    file: `${newPath}/Divlje_jagode_-_Marija-cut.mp3`,
  },
  {
    id: 2,
    title: "Sve još miriše na nju",
    artist: "Parni valjak",
    playlist: "rock",
    // file: `${path}\\Parni_valjak_-_Sve_još_miriše_na_nju.mp3`,
    file: `${newPath}/Parni_valjak_-_Sve_još_miriše_na_nju-cut.mp3`,
  },
  {
    id: 3,
    title: "Previše suza u mom pivu",
    artist: "Prljavo kazalište",
    playlist: "rock",
    // file: `${path}\\Prljavo_kazaliste_-_Previše_suza_u_mom_pivu.mp3`,
    file: `${newPath}/Prljavo_kazaliste_-_Previše_suza_u_mom_pivu-cut.mp3`,
  },
  {
    id: 4,
    title: "Aspirin",
    artist: "Seka",
    playlist: "folk",
    // file: `${path}\\Seka_-_Aspirin.mp3`,
    file: `${newPath}/Seka_-_Aspirin-cut.mp3`,
  },
  {
    id: 5,
    title: "Mešaj, mala (feat. Saša Matić)",
    artist: "Rada Manojlović",
    playlist: "folk",
    // file: `${path}\\Rada_Manojlović_-_Mešaj,_mala_feat._Saša_Matić).mp3`,
    file: `${newPath}/Rada_Manojlović_-_Mešaj,_mala_feat._Saša_Matić-cut.mp3`,
  },
  {
    id: 6,
    title: "Šampanjac",
    artist: "Mile Kitić",
    playlist: "folk",
    // file: `${path}\\Mile_Kitić_-_Šampanjac.mp3`,
    file: `${newPath}/Mile_Kitić_-_Šampanjac-cut.mp3`,
  },
  {
    id: 7,
    title: "Trezan",
    artist: "Sinan Sakić",
    playlist: "folk",
    // file: `${path}\\Sinan_Sakić_-_Trezan.mp3`,
    file: `${newPath}/Sinan_Sakić_-_Trezan-cut.mp3`,
  },
  // {
  //   id: 8,
  //   title: "No sikiriki no",
  //   artist: "Edo Maajka",
  //   playlist: "rap",
  //   file: `${path}\\Edo_Maajka_-_No_sikiriki_no.mp3`,
  // },
  // {
  //   id: 9,
  //   title: "Ne može",
  //   artist: "Vojko V",
  //   playlist: "rap",
  //   file: `${path}\\Vojko_V_-_Ne_može.mp3`,
  // },
  // {
  //   id: 10,
  //   title: "Esi mi dobar",
  //   artist: "Bad Copy",
  //   playlist: "rap",
  //   file: `${path}\\Bad_Copy_-_Esi_mi_dobar.mp3`,
  // },
  // {
  //   id: 11,
  //   title: "Malo san maka",
  //   artist: "The Beat Fleet",
  //   playlist: "rap",
  //   file: `${path}\\The_Beat_Fleet_-_Malo_san_maka.mp3`,
  // },
  {
    id: 12,
    title: "Kiše jesenje",
    artist: "Prljavo kazalište",
    playlist: "rock",
    file: `${newPath}\\Prljavo_kazalište_-_Kiše_jesenje-cut.mp3`,
  },
  {
    id: 13,
    title: "Ja sam budućnost",
    artist: "Majke",
    playlist: "rock",
    file: `${newPath}\\Majke_-_Ja_sam_budućnost-cut.mp3`,
  },
  {
    id: 13,
    title: "Tremolo",
    artist: "Vatra",
    playlist: "rock",
    file: `${newPath}\\Vatra_-_Tremolo-cut.mp3`,
  },
  {
    id: 14,
    title: "Verujem, ne verujem",
    artist: "Bajaga i Instruktori",
    playlist: "rock",
    file: `${newPath}\\Bajaga_i_Instruktori_-_Verujem,_ne_verujem-cut.mp3`,
  },
  {
    id: 15,
    title: "Ne zovi mama doktora",
    artist: "Prljavo kazalište",
    playlist: "rock",
    file: `${newPath}\\Prljavo_kazalište_-_Ne_zovi_mama_doktora-cut.mp3`,
  },
  {
    id: 16,
    title: "Ja volim samo sebe",
    artist: "Psihomodo Pop",
    playlist: "rock",
    file: `${newPath}\\Psihomodo_Pop_-_Ja_volim_samo_sebe-cut.mp3`,
  },
  {
    id: 17,
    title: "Teške boje",
    artist: "Goran Bare i Majke",
    playlist: "rock",
    file: `${newPath}\\Goran_Bare_i_Majke_-_Teške_boje-cut.mp3`,
  },
  {
    id: 18,
    title: "Što si mi u kavu stavila",
    artist: "Pađen band",
    playlist: "rock",
    file: `${newPath}\\Pađen_band_-_Što_si_mi_u_kavu_stavila-cut.mp3`,
  },
  {
    id: 19,
    title: "Napile se ulice",
    artist: "Bijelo dugme",
    playlist: "rock",
    file: `${newPath}\\Bijelo_dugme_-_Napile_se_ulice-cut.mp3`,
  },
  {
    id: 20,
    title: "Mali signali",
    artist: "Nataša Bekvalac",
    playlist: "folk",
    file: `${newPath}\\Nataša_Bekvalac_-_Mali_signali-cut.mp3`,
  },
  {
    id: 21,
    title: "Bele ruže",
    artist: "Aca Lukas",
    playlist: "folk",
    file: `${newPath}\\Aca_Lukas_-_Bele_ruže-cut.mp3`,
  },
  {
    id: 22,
    title: "Ponovo",
    artist: "Nataša Bekvalac",
    playlist: "folk",
    file: `${newPath}\\Nataša_Bekvalac_-_Ponovo-cut.mp3`,
  },
  {
    id: 23,
    title: "Litar na litar",
    artist: "Đani",
    playlist: "folk",
    file: `${newPath}\\Đani_-_Litar_na_litar-cut.mp3`,
  },
  {
    id: 24,
    title: "Zicer",
    artist: "Olja Karleuša",
    playlist: "folk",
    file: `${newPath}\\Olja_Karleuša_-_Zicer-cut.mp3`,
  },
  {
    id: 25,
    title: "Vrati mi se nesrećo",
    artist: "Miligram 3",
    playlist: "folk",
    file: `${newPath}\\Miligram_3_-_Vrati_mi_se_nesrećo-cut.mp3`,
  },
  {
    id: 26,
    title: "Hitna pomoć",
    artist: "Trik FX",
    playlist: "folk",
    file: `${newPath}\\Trik_FX_-_Hitna_pomoć-cut.mp3`,
  },
  {
    id: 27,
    title: "Gljiva ludara",
    artist: "Đogani",
    playlist: "folk",
    file: `${newPath}\\Đogani_-_Gljiva_ludara-cut.mp3`,
  },
  {
    id: 28,
    title: "Jura Stublić i Film",
    artist: "Chicago",
    playlist: "rock",
    file: `${newPath}/Jura_Stublić_i_Film_-_Chicago-cut.mp3`,
  },
  {
    id: 29,
    title: "Jura Stublić i Film",
    artist: "Srce na cesti",
    playlist: "rock",
    file: `${newPath}/Jura_Stublić_i_Film_-_Srce_na_cesti-cut.mp3`,
  },
];
