const path = "C:\\Users\\ekoko\\Downloads";

export const songs = [
  {
    id: 0,
    title: "Kap po kap",
    artist: "Divlje Jagode",
    playlist: "rock",
    file: `${path}\\Divlje_jagode_-_Kap_po_kap.mp3`,
  },
  {
    id: 1,
    title: "Marija",
    artist: "Divlje Jagode",
    playlist: "rock",
    file: `${path}\\Divlje_jagode_-_Marija.mp3`,
  },
  {
    id: 2,
    title: "Sve još miriše na nju",
    artist: "Parni valjak",
    playlist: "rock",
    file: `${path}\\Parni_valjak_-_Sve_još_miriše_na_nju.mp3`,
  },
  {
    id: 3,
    title: "Previše suza u mom pivu",
    artist: "Prljavo kazalište",
    playlist: "rock",
    file: `${path}\\Prljavo_kazaliste_-_Previše_suza_u_mom_pivu.mp3`,
  },
  {
    id: 4,
    title: "Aspirin",
    artist: "Seka",
    playlist: "folk",
    file: `${path}\\Seka_-_Aspirin.mp3`,
  },
  {
    id: 5,
    title: "Mešaj, mala (feat. Saša Matić)",
    artist: "Rada Manojlović",
    playlist: "folk",
    file: `${path}\\Rada_Manojlović_-_Mešaj,_mala_feat._Saša_Matić).mp3`,
  },
  {
    id: 6,
    title: "Šampanjac",
    artist: "Mile Kitić",
    playlist: "folk",
    file: `${path}\\Mile_Kitić_-_Šampanjac.mp3`,
  },
  {
    id: 7,
    title: "Trezan",
    artist: "Sinan Sakić",
    playlist: "folk",
    file: `${path}\\Sinan_Sakić_-_Trezan.mp3`,
  },
  {
    id: 8,
    title: "No sikiriki no",
    artist: "Edo Maajka",
    playlist: "rap",
    file: `${path}\\Edo_Maajka_-_No_sikiriki_no.mp3`,
  },
  {
    id: 9,
    title: "Ne može",
    artist: "Vojko V",
    playlist: "rap",
    file: `${path}\\Vojko_V_-_Ne_može.mp3`,
  },
  {
    id: 10,
    title: "Esi mi dobar",
    artist: "Bad Copy",
    playlist: "rap",
    file: `${path}\\Bad_Copy_-_Esi_mi_dobar.mp3`,
  },
  {
    id: 11,
    title: "Malo san maka",
    artist: "The Beat Fleet",
    playlist: "rap",
    file: `${path}\\The_Beat_Fleet_-_Malo_san_maka.mp3`,
  },
];
