export const users = [
  {
    id: 0,
    name: "Dino Merlić(0)",
    playlists: ["Rock", "Rap"],
    friends: [1, 2],
    // duels: ["10"],
    duels: [],
    coins: 43,
    "games played": 12,
    "games won": 7,
    "games lost": 3,
    "games tied": 2,
    achievements: [
      { id: 0, mission: "Win 10 games", progress: 7, total: 10 },
      {
        id: 1,
        mission: "Win a match agains 3 different people",
        progress: 3,
        total: 3,
      },
      {
        id: 2,
        mission: "Win with 5 different playlists",
        progress: 3,
        total: 5,
      },
      { id: 3, mission: "Earn a score of 250", progress: 1, total: 1 },
      { id: 4, mission: "Earn a score of 300", progress: 0, total: 1 }, // Perfectionist
    ],
  },
  {
    id: 1,
    name: "Senka Miletić(1)",
    playlists: ["Rock", "Folk"],
    friends: [0],
    // duels: ["10", "21"],
    duels: [],
    coins: 10,
    "games played": 6,
    "games won": 2,
    "games lost": 4,
    "games tied": 0,
    achievements: [
      { id: 0, mission: "Win 10 games", progress: 1, total: 10 },
      {
        id: 1,
        mission: "Win a match agains 3 different people",
        progress: 3,
        total: 3,
      },
      {
        id: 2,
        mission: "Win with 5 different playlists",
        progress: 2,
        total: 5,
      },
      { id: 3, mission: "Earn a score of 250", progress: 0, total: 1 },
      { id: 4, mission: "Earn a score of 300", progress: 0, total: 1 }, // Perfectionist
    ],
  },
  {
    id: 2,
    name: "Fedja Sakić(2)",
    playlists: ["Folk", "Rap"],
    friends: [0],
    // duels: ["21"],
    duels: [],
    coins: 3,
    "games played": 3,
    "games won": 0,
    "games lost": 3,
    "games tied": 0,
    achievements: [
      { id: 0, mission: "Win 10 games", progress: 0, total: 10 },
      {
        id: 1,
        mission: "Win a match agains 3 different people",
        progress: 0,
        total: 3,
      },
      {
        id: 2,
        mission: "Win with 5 different playlists",
        progress: 0,
        total: 5,
      },
      { id: 3, mission: "Earn a score of 250", progress: 0, total: 1 },
      { id: 4, mission: "Earn a score of 300", progress: 0, total: 1 }, // Perfectionist
    ],
  },
  {
    id: 3,
    name: "Milan Swarovski(3)",
    playlists: ["Folk"],
    friends: [],
    duels: [],
    coins: 5,
    "games played": 2,
    "games won": 1,
    "games lost": 3,
    "games tied": 1,
    achievements: [
      { id: 0, mission: "Win 10 games", progress: 1, total: 10 },
      {
        id: 1,
        mission: "Win a match agains 3 different people",
        progress: 1,
        total: 3,
      },
      {
        id: 2,
        mission: "Win with 5 different playlists",
        progress: 1,
        total: 5,
      },
      { id: 3, mission: "Earn a score of 250", progress: 0, total: 1 },
      { id: 4, mission: "Earn a score of 300", progress: 0, total: 1 }, // Perfectionist
    ],
  },
  {
    id: 4,
    name: "Jurica Novak(4)",
    playlists: ["Folk"],
    friends: [],
    duels: [],
    coins: 10,
    "games played": 5,
    "games won": 2,
    "games lost": 2,
    "games tied": 1,
    achievements: [
      { id: 0, mission: "Win 10 games", progress: 2, total: 10 },
      {
        id: 1,
        mission: "Win a match agains 3 different people",
        progress: 2,
        total: 3,
      },
      {
        id: 2,
        mission: "Win with 5 different playlists",
        progress: 2,
        total: 5,
      },
      { id: 3, mission: "Earn a score of 250", progress: 1, total: 1 },
      { id: 4, mission: "Earn a score of 300", progress: 0, total: 1 }, // Perfectionist
    ],
  },
];
