export const users = [
  {
    id: 0,
    name: "Dino Merlić",
    playlists: ["rock", "rap"],
    friends: [1, 2],
    coins: 43,
    "games played": 12,
    "games won": 7,
    "games lost": 3,
    "games tied": 2,
  },
  {
    id: 1,
    name: "Senka Miletić",
    playlists: ["rock", "trap"],
    friends: [0],
    coins: 10,
    "games played": 6,
    "games won": 2,
    "games lost": 4,
    "games tied": 0,
  },
  {
    id: 2,
    name: "Fedja Sakić",
    playlists: ["folk", "rap"],
    friends: [0],
    coins: 3,
    "games played": 3,
    "games won": 0,
    "games lost": 3,
    "games tied": 0,
  },
  {
    id: 3,
    name: "Milan Swarovski",
    playlists: ["folk"],
    friends: [],
    coins: 5,
    "games played": 2,
    "games won": 1,
    "games lost": 3,
    "games tied": 1,
  },
];
