export const users = [
  {
    id: 0,
    name: "Dino Merlić",
    playlists: ["rock", "rap"],
    duels: [],
    coins: 43,
    // medals: ["won 10 games"],
    "games played": 12,
    "games won": 7,
    "games lost": 3,
    "games tied": 2,
  },
  {
    id: 1,
    name: "Senka Miletić",
    playlists: ["rock", "trap"],
    duels: [{ against: 2, playlist: "rock", played: 1, score: 75 }],
    coins: 10,
    // medals: ["won with a perfect score"],
    "games played": 6,
    "games won": 2,
    "games lost": 4,
    "games tied": 0,
  },
  {
    id: 2,
    name: "Fedja Sakić",
    playlists: ["folk", "rap"],
    duels: [{ against: 1, playlist: "rock", played: 0, score: 0 }],
    coins: 3,
    // medals: [],
    "games played": 3,
    "games won": 0,
    "games lost": 3,
    "games tied": 0,
  },
];
